# -*- coding: utf-8 -*-
{
    'name': "syndicom Vollzug",
    'author': "syndicom, Pascal Arnold",
    'website': "https://syndicom.ch",
    'category': 'Sales/CRM',
    'version': '15.0.1.0.2',
    'license': 'LGPL-3',
    'summary': "Vollzug",
    'description': "Modul zum verwalten der GAV-Unterstellungen und entsprechenden Deklarationsaufforderungen",
    'depends': [
        'base',
        'contacts',
        'mass_mailing',
        'industry_fsm',
    ],
    'data': [
        'security/vollzug_officer.xml',
        'security/ir.model.access.csv',
        'views/inherited_res_config_settings.xml',
        'views/vollzug_declaration.xml',
        'views/vollzug_declaration_check.xml',
        'views/vollzug_declaration_person.xml',
        'views/vollzug_stages.xml',
        'views/vollzug_declaration_wizard.xml',
        'views/vollzug_notice.xml',
        'views/vollzug_declaration_wizard_reminder.xml',
        'views/inherited_res_partner_form_view.xml',
        'views/inherited_project_task.xml',
        'views/menu.xml',
        'data/data.xml',
    ],
    'auto_install': False,
    'installable': True,
    'application': True,
}
